# Generated by Django 3.1.3 on 2021-03-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='date_now',
            field=models.DateField(auto_now=True),
        ),
    ]
