# Generated by Django 3.1.3 on 2021-03-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0002_exam_date_now'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='points',
        ),
        migrations.AddField(
            model_name='student',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
